name: wallet_track
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI and icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.5.0
  flutter_slidable: ^3.0.1
  flutter_spinkit: ^5.2.0
  pie_chart: ^5.3.2
  syncfusion_flutter_charts: ^23.1.44

  # State / storage / utilities
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  uuid: ^4.1.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  path_provider: ^2.1.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/Logo.jpg"

flutter:
  uses-material-design: true

  assets:
    - images/download.png
    - images/Logo.jpg

  # Fonts (uncomment and modify if you need custom fonts)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
